apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-recipient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-recipient
  template:
    metadata:
      labels:
        app: micro-recipient
    spec:
      containers:
        - name: micro-recipient
          image: saulcolin9/micro-recipient:latest
          ports:
            - containerPort: 8081