services:
  micro-sender:
    container_name: micro-sender
    image: micro-sender:latest
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - sender

  micro-recipient:
    container_name: micro-recipient
    image: micro-recipient:latest
    ports:
      - "8081:8081"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - recipient

  micro-collector:
    container_name: micro-collector
    image: micro-collector:latest
    ports:
      - "8082:8082"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - recipient

  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBIT_DEFAULT_PASS=guest
    networks:
      - sender
      - recipient

networks:
  sender:
    driver: bridge
  recipient:
    driver: bridge