apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-collector
  template:
    metadata:
      labels:
        app: micro-collector
    spec:
      containers:
        - name: micro-collector
          image: saulcolin9/micro-collector:latest
          ports:
            - containerPort: 8082