apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    scrape_configs:
    - job_name: 'micro-sender-metrics'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 3s
      static_configs:
        - targets: ['micro-sender.default.svc.cluster.local:8080', 'micro-visualizer.default.svc.cluster.local:8084']
          labels:
            application: 'Micro-sender application service'

    - job_name: 'micro-collector-metrics'
      scrape_interval: 3s
      metrics_path: '/actuator/prometheus'
      kubernetes_sd_configs:
        - role: endpoints
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          regex: micro-collector
          action: keep
        - source_labels: [__meta_kubernetes_namespace]
          regex: default
          action: keep
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod