scrape_configs:
  - job_name: 'micro-sender-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['micro-sender:8080']
        labels:
          application: 'Micro-sender application service'